import { Router } from 'express';
import {
  startBot,
  stopBot,
  getBotStatus,
  getAllBotStatuses,
} from '../services/bot-manager.service.js';
import { runBacktest } from '../services/backtest.service.js';
import { resolveAdxFilterOptions } from '../services/adx-filter.service.js';
import config from '../config/index.js';
import BotLog from '../models/bot-log.model.js';
import Signal from '../models/signal.model.js';

const router = Router();

/**
 * GET /api/bots
 * List all available strategies and their active/inactive status.
 */
router.get('/', async (_req, res) => {
  const bots = await getAllBotStatuses();
  res.json({
    bots,
    adxFilter: resolveAdxFilterOptions(),
    availableSymbols: config.binance.symbols,
  });
});

/**
 * POST /api/bots/backtest
 * Run a backtest for any strategy on stored candle data.
 * Body: { strategy?, symbol?, startBalance?, leverage?, feePercent?, slPercent?, tpPercent?, adxFilterEnabled?, adxPeriod?, adxThreshold? }
 */
router.post('/backtest', async (req, res) => {
  try {
    const result = await runBacktest({
      strategy: req.body.strategy,
      symbol: req.body.symbol,
      startBalance: req.body.startBalance,
      leverage: req.body.leverage,
      feePercent: req.body.feePercent,
      slPercent: req.body.slPercent,
      tpPercent: req.body.tpPercent,
      adxFilterEnabled: req.body.adxFilterEnabled,
      adxPeriod: req.body.adxPeriod,
      adxThreshold: req.body.adxThreshold,
    });
    res.json(result);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

/**
 * GET /api/bots/:strategy
 * Get status for a specific bot.
 */
router.get('/:strategy', async (req, res) => {
  const status = await getBotStatus(req.params.strategy);
  if (!status) {
    return res.status(404).json({ error: `Strategy "${req.params.strategy}" not found` });
  }
  res.json(status);
});

/**
 * POST /api/bots/:strategy/start
 * Start a bot for the given strategy.
 */
router.post('/:strategy/start', async (req, res) => {
  try {
    const result = await startBot(req.params.strategy, req.body || {});
    res.json(result);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

/**
 * POST /api/bots/:strategy/stop
 * Stop a bot for the given strategy.
 */
router.post('/:strategy/stop', (req, res) => {
  const result = stopBot(req.params.strategy);
  res.json(result);
});

/**
 * GET /api/bots/:strategy/logs
 * Get transaction logs for a specific bot.
 * Query params: ?limit=50&symbol=BTCUSDT
 */
router.get('/:strategy/logs', async (req, res) => {
  const { strategy } = req.params;
  const limit = Math.min(parseInt(req.query.limit, 10) || 50, 200);
  const query = { strategy };

  if (req.query.symbol) {
    query.symbol = req.query.symbol.toUpperCase();
  }

  const logs = await BotLog.find(query)
    .sort({ createdAt: -1 })
    .limit(limit)
    .lean();

  res.json({ strategy, count: logs.length, logs });
});

/**
 * GET /api/bots/:strategy/signals
 * Get signals generated by a specific bot.
 * Query params: ?limit=50&symbol=BTCUSDT
 */
router.get('/:strategy/signals', async (req, res) => {
  const { strategy } = req.params;
  const limit = Math.min(parseInt(req.query.limit, 10) || 50, 200);
  const query = { strategy };

  if (req.query.symbol) {
    query.symbol = req.query.symbol.toUpperCase();
  }

  const signals = await Signal.find(query)
    .sort({ createdAt: -1 })
    .limit(limit)
    .lean();

  res.json({ strategy, count: signals.length, signals });
});

export default router;
